language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - NUMX=numpy
  - NUMX=scipy
virtualenv:
  system_site_packages: true
# command to install dependencies
before_install:
  - export NUMX_PREFIX=$( [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ] && echo "python3" || echo "python" )
  - export NUMX_PACKAGE="$NUMX_PREFIX-$NUMX"
install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get install -qq $NUMX_PACKAGE
#  - "pip install $NUMX --use-mirrors"
# command to run tests
script: "python setup.py install --home=~ && cd ~/lib/python && PYTHONPATH=. python -c 'import mdp;mdp.test()'"
