language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - NUMX=python-numpy
  - NUMX=python-scipy
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get install -qq $NUMX
#  - "pip install $NUMX --use-mirrors"
# command to run tests
script: "python setup.py install --home=~ && cd ~/lib/python && PYTHONPATH=. python -c 'import mdp;mdp.test()'"
