language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - NUMX=numpy
  - NUMX=scipy
# command to install dependencies
install:
  - "pip install $NUMX --use-mirrors"
# command to run tests
script: "python setup.py install --home=~ && cd ~/lib/python && PYTHONPATH=. python -c 'import mdp;mdp.test()'"
